apiVersion: v1
kind: Secret
metadata:
  name: server-credentials
type: Opaque
data:
  rootpasswd: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashuj-server
  labels:
    app: hashuj-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashuj-server
      version: v1
  template:
    metadata:
      labels:
        app: hashuj-server
        version: v1
    spec:      
      serviceAccountName: default
      containers:
      - name: hashuj-server
        image: image-registry.openshift-image-registry.svc:5000/labproj24/server:26.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: server-credentials
                key: rootpasswd
        resources: {}
        envFrom:
        - configMapRef:
            name: cmap-server
status: {}
