apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-26T09:57:39Z"
  labels:
    app: hashuj-server
    version: v1
  name: hashuj-server-svc
  namespace: labproj24
  resourceVersion: "80416904"
  uid: 4e12595f-e750-43a4-96d6-cc31b5880a94
spec:
  clusterIP: 172.30.76.64
  clusterIPs:
  - 172.30.76.64
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: hashuj-server
    version: v1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
